# Generated by Django 5.2.2 on 2025-07-22 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("choosable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("serial", models.CharField(max_length=255, unique=True)),
                (
                    "cpu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("i3", "Intel Core i3"),
                            ("i5", "Intel Core i5"),
                            ("i7", "Intel Core i7"),
                            ("i9", "Intel Core i9"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cpu_generation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1th\u202fGen"),
                            ("2", "2th\u202fGen"),
                            ("3", "3th\u202fGen"),
                            ("4", "4th\u202fGen"),
                            ("5", "5th\u202fGen"),
                            ("6", "6th\u202fGen"),
                            ("7", "7th\u202fGen"),
                            ("8", "8th\u202fGen"),
                            ("9", "9th\u202fGen"),
                            ("10", "10th\u202fGen"),
                            ("11", "11th\u202fGen"),
                            ("12", "12th\u202fGen"),
                            ("13", "13th\u202fGen"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4GB", "4 GB"),
                            ("8GB", "8 GB"),
                            ("16GB", "16 GB"),
                            ("32GB", "32 GB"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Use", "In Use"),
                            ("Stock", "Stock"),
                            ("Damage", "Damage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("warranty", models.DateField(blank=True, null=True)),
                ("on_hand_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Laptop", "Laptop"), ("Desktop", "Desktop")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(max_length=20)),
                ("on_hand_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "change_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assets.asset",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.branch",
                    ),
                ),
                (
                    "new_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_employee_logs",
                        to="assets.employee",
                    ),
                ),
                (
                    "old_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_employee_logs",
                        to="assets.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Log",
                "verbose_name_plural": "Asset Logs",
                "ordering": ["-change_time"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="employee_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.employee",
            ),
        ),
        migrations.CreateModel(
            name="StorageDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("HDD", "HDD"), ("SSD", "SSD")], max_length=10
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("128", "128 GB"),
                            ("256", "256 GB"),
                            ("512", "512 GB"),
                            ("1TB", "1 TB"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_devices",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
