# Generated by Django 5.2.2 on 2025-07-23 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_employee_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportableModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_path",
                    models.CharField(
                        help_text="Dotted path to model, e.g. 'assets.Asset'",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="asset",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assetlog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ReportableField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Exact field or dotted path (e.g. 'branch__name')",
                        max_length=100,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for UI", max_length=100
                    ),
                ),
                ("is_filter", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("char", "CharField / Text"),
                            ("choice", "Choice Field (dropdown)"),
                            ("foreign", "ForeignKey (name/display)"),
                            ("date", "Date Field"),
                            ("numeric", "Integer / Float"),
                        ],
                        default="char",
                        max_length=20,
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="Only for 'choice' fields: list of allowed values",
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="assets.reportablemodel",
                    ),
                ),
            ],
        ),
    ]
