# Generated by Django 5.1.5 on 2025-07-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_screen_screenlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
