# Generated by Django 5.1.5 on 2025-07-30 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_screen_brand"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="brand",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Serial Number"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Stock", "Stock"),
                            ("In Use", "In Use"),
                            ("Damage", "Damage"),
                        ],
                        default="Stock",
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("power_source", models.CharField(max_length=100)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
            },
        ),
        migrations.CreateModel(
            name="CameraLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(max_length=20)),
                (
                    "old_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("new_location", models.CharField(max_length=200)),
                (
                    "change_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assets.camera",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_new_branch",
                        to="assets.branch",
                    ),
                ),
                (
                    "old_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_old_branch",
                        to="assets.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera Log",
                "verbose_name_plural": "Camera Logs",
            },
        ),
        migrations.CreateModel(
            name="NVR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Serial Number"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Stock", "Stock"),
                            ("In Use", "In Use"),
                            ("Damage", "Damage"),
                        ],
                        default="Stock",
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("hdd_capacity", models.CharField(max_length=50)),
                ("number_of_ports", models.PositiveIntegerField()),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NVR",
                "verbose_name_plural": "NVRs",
            },
        ),
        migrations.CreateModel(
            name="NVRLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(max_length=20)),
                (
                    "old_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("new_location", models.CharField(max_length=200)),
                (
                    "change_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_new_branch",
                        to="assets.branch",
                    ),
                ),
                (
                    "nvr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assets.nvr",
                    ),
                ),
                (
                    "old_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_old_branch",
                        to="assets.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "NVR Log",
                "verbose_name_plural": "NVR Logs",
            },
        ),
    ]
