# Generated by Django 5.1.5 on 2025-07-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_alter_screen_brand_camera_cameralog_nvr_nvrlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameralog",
            name="new_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="nvrlog",
            name="new_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
