# Generated by Django 5.1.5 on 2025-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_cameralog_new_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameralog",
            name="new_location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="nvrlog",
            name="new_location",
            field=models.CharField(default="stock", max_length=200),
            preserve_default=False,
        ),
    ]
