# Generated by Django 5.1.5 on 2025-07-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_firewall_firewalllog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firewall",
            old_name="license_expiry",
            new_name="license_expiry_date",
        ),
    ]
