# Generated by Django 5.1.5 on 2025-08-07 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_accesspoint_accesspointlog_router_routerlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                ("is_required", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["model_name", "field_name"],
                "unique_together": {("model_name", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="UPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Serial Number"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Stock", "Stock"),
                            ("In Use", "In Use"),
                            ("Damage", "Damage"),
                        ],
                        default="Stock",
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("voltage", models.FloatField(blank=True, null=True)),
                (
                    "power_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Utility", "Utility"),
                            ("Battery", "Battery"),
                            ("Generator", "Generator"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UPS",
                "verbose_name_plural": "UPS Devices",
            },
        ),
        migrations.CreateModel(
            name="UPSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(max_length=20)),
                (
                    "old_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("new_location", models.CharField(max_length=200)),
                (
                    "change_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("old_voltage", models.FloatField(blank=True, null=True)),
                ("new_voltage", models.FloatField(blank=True, null=True)),
                (
                    "old_power_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Utility", "Utility"),
                            ("Battery", "Battery"),
                            ("Generator", "Generator"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_power_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Utility", "Utility"),
                            ("Battery", "Battery"),
                            ("Generator", "Generator"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("old_last_maintenance_date", models.DateField(blank=True, null=True)),
                ("new_last_maintenance_date", models.DateField(blank=True, null=True)),
                ("old_next_maintenance_date", models.DateField(blank=True, null=True)),
                ("new_next_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_new_branch",
                        to="assets.branch",
                    ),
                ),
                (
                    "old_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_old_branch",
                        to="assets.branch",
                    ),
                ),
                (
                    "ups",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assets.ups",
                    ),
                ),
            ],
            options={
                "verbose_name": "UPS Log",
                "verbose_name_plural": "UPS Logs",
            },
        ),
    ]
