# Generated by Django 5.1.5 on 2025-08-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_fieldbehavior_ups_upslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="firewall",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="nvr",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="switch",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
        migrations.AlterField(
            model_name="ups",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.branch",
            ),
        ),
    ]
