# Generated by Django 5.1.5 on 2025-08-16 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_alter_accesspoint_branch_alter_camera_branch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RayaDataCenterVM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(protocol="IPv4")),
                (
                    "vcpu",
                    models.PositiveIntegerField(help_text="Number of vCPUs (in cores)"),
                ),
                ("vram_gb", models.PositiveIntegerField(help_text="vRAM in GB")),
                (
                    "allocated_storage_gb",
                    models.PositiveIntegerField(
                        default=0, help_text="Allocated Storage in GB"
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(default="Ubuntu Linux", max_length=100),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[("uat", "UAT"), ("prod", "Production")], max_length=20
                    ),
                ),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Raya Data Center VM",
                "verbose_name_plural": "Raya Data Center VMs",
                "ordering": ["environment", "name"],
            },
        ),
    ]
