# Generated by Django 5.1.5 on 2025-08-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0015_rayadatacentervm_comments_zkdevice_zkdevicelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="zkdevice",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
