# Generated by Django 5.1.5 on 2025-08-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0016_zkdevice_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zkdevice",
            name="comments",
        ),
    ]
