# Generated by Django 5.1.5 on 2025-08-22 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0017_remove_zkdevice_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Serial Number"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Stock", "Stock"),
                            ("In Use", "In Use"),
                            ("Damage", "Damage"),
                        ],
                        default="Stock",
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("hostname", models.CharField(max_length=100, unique=True)),
                (
                    "cpu_cores",
                    models.PositiveIntegerField(help_text="Total physical CPU cores"),
                ),
                ("ram_gb", models.PositiveIntegerField(help_text="Total RAM in GB")),
                (
                    "storage_gb",
                    models.PositiveIntegerField(help_text="Total storage in GB"),
                ),
                (
                    "hypervisor",
                    models.CharField(
                        choices=[("vmware", "VMware ESXi"), ("hyperv", "Hyper-V")],
                        max_length=20,
                    ),
                ),
                (
                    "available_cpu_cores",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "available_ram_gb",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "available_storage_gb",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(max_length=20)),
                (
                    "old_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("new_location", models.CharField(max_length=200)),
                (
                    "change_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_new_branch",
                        to="assets.branch",
                    ),
                ),
                (
                    "old_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_old_branch",
                        to="assets.branch",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assets.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-change_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VirtualMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("operating_system", models.CharField(default="Linux", max_length=100)),
                ("vcpu", models.PositiveIntegerField(help_text="Allocated vCPUs")),
                (
                    "vram_gb",
                    models.PositiveIntegerField(help_text="Allocated RAM (GB)"),
                ),
                (
                    "storage_gb",
                    models.PositiveIntegerField(help_text="Allocated Storage (GB)"),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("uat", "UAT"),
                            ("prod", "Production"),
                            ("dev", "Development"),
                            ("test", "Testing"),
                        ],
                        default="prod",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("stopped", "Stopped")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vms",
                        to="assets.server",
                    ),
                ),
            ],
            options={
                "ordering": ["server", "name"],
                "unique_together": {("server", "name")},
            },
        ),
        migrations.CreateModel(
            name="VirtualMachineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(max_length=20)),
                (
                    "change_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assets.virtualmachine",
                    ),
                ),
            ],
            options={
                "ordering": ["-change_time"],
            },
        ),
    ]
