# Generated by Django 5.1.5 on 2025-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0018_server_serverlog_virtualmachine_virtualmachinelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverlog",
            name="new_cpu",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverlog",
            name="new_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverlog",
            name="new_ram",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverlog",
            name="new_storage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverlog",
            name="old_cpu",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverlog",
            name="old_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverlog",
            name="old_ram",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverlog",
            name="old_storage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
