# Generated by Django 5.1.5 on 2025-09-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0019_serverlog_new_cpu_serverlog_new_ip_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("Asset", "Asset"),
                            ("Screen", "Screen"),
                            ("Telephone", "Telephone"),
                            ("Camera", "Camera"),
                            ("NVR", "NVR"),
                            ("Firewall", "Firewall"),
                            ("Switch", "Switch"),
                            ("AccessPoint", "Access Point"),
                            ("Router", "Router"),
                            ("UPS", "UPS"),
                            ("ZKDevice", "ZK Device"),
                            ("Server", "Server"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("stock_count", "Stock Count"),
                            ("status", "Status Change"),
                            ("warranty", "Warranty Expiry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        help_text="For stock: number, for status: status value, for warranty: days before expiry",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notification_message",
                    models.TextField(
                        blank=True,
                        help_text="Custom message for the notification. Use {model}, {count}, {threshold} as variables",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("model_name", "condition_type", "condition_value")
                },
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "models_to_notify",
                    models.ManyToManyField(blank=True, to="assets.notificationconfig"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_by", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.notificationconfig",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.notificationrecipient",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
