# Generated by Django 5.1.5 on 2025-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0020_notificationconfig_notificationrecipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationconfig",
            name="condition_type",
            field=models.CharField(
                choices=[("stock_count", "Stock Count")], max_length=20
            ),
        ),
    ]
