# Generated by Django 4.2.26 on 2026-08-27 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def copy_assets(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    AssetLog = apps.get_model("assets", "AssetLog")
    StorageDevice = apps.get_model("assets", "StorageDevice")
    Laptop = apps.get_model("assets", "Laptop")
    Desktop = apps.get_model("assets", "Desktop")
    LaptopLog = apps.get_model("assets", "LaptopLog")
    DesktopLog = apps.get_model("assets", "DesktopLog")
    LaptopStorage = apps.get_model("assets", "LaptopStorage")
    DesktopStorage = apps.get_model("assets", "DesktopStorage")
    NotificationConfig = apps.get_model("assets", "NotificationConfig")

    laptop_map = {}
    desktop_map = {}

    for asset in Asset.objects.all().iterator():
        fields = {
            "product": asset.product,
            "serial": asset.serial,
            "cpu": asset.cpu,
            "cpu_generation": asset.cpu_generation,
            "ram": asset.ram,
            "status": asset.status,
            "employee_id": asset.employee_name_id,
            "warranty": asset.warranty,
            "on_hand_date": asset.on_hand_date,
            "return_date": asset.return_date,
            "comments": asset.comments,
            "branch_id": asset.branch_id,
            "created_by_id": asset.created_by_id,
        }
        if (asset.type or "").lower() == "desktop":
            obj = Desktop.objects.create(**fields)
            desktop_map[asset.id] = obj.id
        else:
            obj = Laptop.objects.create(**fields)
            laptop_map[asset.id] = obj.id

    for storage in StorageDevice.objects.all().iterator():
        if storage.asset_id in laptop_map:
            LaptopStorage.objects.create(
                laptop_id=laptop_map[storage.asset_id],
                type=storage.type,
                size=storage.size,
            )
        elif storage.asset_id in desktop_map:
            DesktopStorage.objects.create(
                desktop_id=desktop_map[storage.asset_id],
                type=storage.type,
                size=storage.size,
            )

    for log in AssetLog.objects.all().iterator():
        shared = {
            "changed_by_id": log.changed_by_id,
            "old_status": log.old_status,
            "new_status": log.new_status,
            "old_employee_id": log.old_employee_id,
            "new_employee_id": log.new_employee_id,
            "on_hand_date": log.on_hand_date,
            "return_date": log.return_date,
            "branch_id": log.branch_id,
            "change_time": log.change_time,
        }
        if log.asset_id in laptop_map:
            LaptopLog.objects.create(laptop_id=laptop_map[log.asset_id], **shared)
        elif log.asset_id in desktop_map:
            DesktopLog.objects.create(desktop_id=desktop_map[log.asset_id], **shared)

    NotificationConfig.objects.filter(model_name="Asset").update(model_name="Laptop")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0021_alter_notificationconfig_condition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('cpu', models.CharField(blank=True, choices=[('i3', 'Intel Core i3'), ('i5', 'Intel Core i5'), ('i7', 'Intel Core i7'), ('i9', 'Intel Core i9')], max_length=20, null=True)),
                ('cpu_generation', models.CharField(blank=True, choices=[('1', '1st Gen'), ('2', '2nd Gen'), ('3', '3rd Gen'), ('4', '4th Gen'), ('5', '5th Gen'), ('6', '6th Gen'), ('7', '7th Gen'), ('8', '8th Gen'), ('9', '9th Gen'), ('10', '10th Gen'), ('11', '11th Gen'), ('12', '12th Gen'), ('13', '13th Gen')], max_length=3, null=True)),
                ('ram', models.CharField(blank=True, choices=[('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('Stock', 'Stock'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20)),
                ('warranty', models.DateField(blank=True, null=True)),
                ('on_hand_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desktop',
                'verbose_name_plural': 'Desktops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesktopLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('on_hand_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('change_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Desktop Log',
                'verbose_name_plural': 'Desktop Logs',
                'ordering': ['-change_time'],
            },
        ),
        migrations.CreateModel(
            name='DesktopStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=10)),
                ('size', models.CharField(choices=[('128', '128 GB'), ('256', '256 GB'), ('512', '512 GB'), ('1TB', '1 TB')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('cpu', models.CharField(blank=True, choices=[('i3', 'Intel Core i3'), ('i5', 'Intel Core i5'), ('i7', 'Intel Core i7'), ('i9', 'Intel Core i9')], max_length=20, null=True)),
                ('cpu_generation', models.CharField(blank=True, choices=[('1', '1st Gen'), ('2', '2nd Gen'), ('3', '3rd Gen'), ('4', '4th Gen'), ('5', '5th Gen'), ('6', '6th Gen'), ('7', '7th Gen'), ('8', '8th Gen'), ('9', '9th Gen'), ('10', '10th Gen'), ('11', '11th Gen'), ('12', '12th Gen'), ('13', '13th Gen')], max_length=3, null=True)),
                ('ram', models.CharField(blank=True, choices=[('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('Stock', 'Stock'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20)),
                ('warranty', models.DateField(blank=True, null=True)),
                ('on_hand_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaptopLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('on_hand_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('change_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Laptop Log',
                'verbose_name_plural': 'Laptop Logs',
                'ordering': ['-change_time'],
            },
        ),
        migrations.CreateModel(
            name='LaptopStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=10)),
                ('size', models.CharField(choices=[('128', '128 GB'), ('256', '256 GB'), ('512', '512 GB'), ('1TB', '1 TB')], max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='accesspointlog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Access Point Log', 'verbose_name_plural': 'Access Point Logs'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='cameralog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Camera Log', 'verbose_name_plural': 'Camera Logs'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='firewall',
            options={'verbose_name': 'Firewall', 'verbose_name_plural': 'Firewalls'},
        ),
        migrations.AlterModelOptions(
            name='firewalllog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Firewall Log', 'verbose_name_plural': 'Firewall Logs'},
        ),
        migrations.AlterModelOptions(
            name='nvrlog',
            options={'ordering': ['-change_time'], 'verbose_name': 'NVR Log', 'verbose_name_plural': 'NVR Logs'},
        ),
        migrations.AlterModelOptions(
            name='routerlog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Router Log', 'verbose_name_plural': 'Router Logs'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterModelOptions(
            name='serverlog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Server Log', 'verbose_name_plural': 'Server Logs'},
        ),
        migrations.AlterModelOptions(
            name='switchlog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Switch Log', 'verbose_name_plural': 'Switch Logs'},
        ),
        migrations.AlterModelOptions(
            name='telephone',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telephone', 'verbose_name_plural': 'Telephones'},
        ),
        migrations.AlterModelOptions(
            name='telephonelog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Telephone Log', 'verbose_name_plural': 'Telephone Logs'},
        ),
        migrations.AlterModelOptions(
            name='upslog',
            options={'ordering': ['-change_time'], 'verbose_name': 'UPS Log', 'verbose_name_plural': 'UPS Logs'},
        ),
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'ordering': ['server', 'name'], 'verbose_name': 'Virtual Machine', 'verbose_name_plural': 'Virtual Machines'},
        ),
        migrations.AlterModelOptions(
            name='virtualmachinelog',
            options={'ordering': ['-change_time'], 'verbose_name': 'Virtual Machine Log', 'verbose_name_plural': 'Virtual Machine Logs'},
        ),
        migrations.AlterModelOptions(
            name='zkdevicelog',
            options={'ordering': ['-change_time'], 'verbose_name': 'ZK Device Log', 'verbose_name_plural': 'ZK Device Logs'},
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_points', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='accesspointlog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesspointlog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='accesspointlog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesspointlog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cameras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='cameralog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameralog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='cameralog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameralog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewalls', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_firewalls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='firewalllog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewalllog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='firewalllog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewalllog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='condition_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='model_name',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Screen', 'Screen'), ('Telephone', 'Telephone'), ('Camera', 'Camera'), ('NVR', 'NVR'), ('Firewall', 'Firewall'), ('Switch', 'Switch'), ('AccessPoint', 'Access Point'), ('Router', 'Router'), ('UPS', 'UPS'), ('ZKDevice', 'ZK Device'), ('Server', 'Server')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='notification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nvrs', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nvrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='nvrlog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nvrlog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='nvrlog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nvrlog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='rayadatacentervm',
            name='allocated_storage_gb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rayadatacentervm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_raya_vms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rayadatacentervm',
            name='vcpu',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rayadatacentervm',
            name='vram_gb',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reportablefield',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportablefield',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportablefield',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportablemodel',
            name='model_path',
            field=models.CharField(help_text="Dotted path to model, e.g. 'assets.Laptop'", max_length=100),
        ),
        migrations.AlterField(
            model_name='router',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='router',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='router',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='routerlog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routerlog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='routerlog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routerlog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='assets.employee'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Damage', 'Damage'), ('Stock', 'Stock')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_cores',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='ram_gb',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='storage_gb',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='serverlog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serverlog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='serverlog',
            name='new_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serverlog',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serverlog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serverlog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_switches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='switch',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='switchlog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switchlog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='switchlog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switchlog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephones', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephones', to='assets.employee'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Damage', 'Damage'), ('Stock', 'Stock')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='ups',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ups_devices', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ups_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ups',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ups',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='upslog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upslog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='upslog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upslog_old_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], db_index=True, default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='storage_gb',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='vcpu',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='vram_gb',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zkdevice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zk_devices', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='zkdevice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zk_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zkdevice',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zkdevice',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Damage', 'Damage')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='zkdevicelog',
            name='new_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zkdevicelog_new_branch', to='assets.branch'),
        ),
        migrations.AlterField(
            model_name='zkdevicelog',
            name='old_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zkdevicelog_old_branch', to='assets.branch'),
        ),
        migrations.AddIndex(
            model_name='accesspoint',
            index=models.Index(fields=['branch', 'status'], name='assets_acce_branch__84cb01_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspoint',
            index=models.Index(fields=['expiry_date'], name='assets_acce_expiry__950b23_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['branch', 'status'], name='assets_came_branch__377a81_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['ip_address'], name='assets_came_ip_addr_aafe56_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch', 'department'], name='assets_empl_branch__79349e_idx'),
        ),
        migrations.AddIndex(
            model_name='firewall',
            index=models.Index(fields=['branch', 'status'], name='assets_fire_branch__a9b67d_idx'),
        ),
        migrations.AddIndex(
            model_name='firewall',
            index=models.Index(fields=['license_expiry_date'], name='assets_fire_license_f9ae43_idx'),
        ),
        migrations.AddIndex(
            model_name='nvr',
            index=models.Index(fields=['branch', 'status'], name='assets_nvr_branch__baaca3_idx'),
        ),
        migrations.AddIndex(
            model_name='rayadatacentervm',
            index=models.Index(fields=['environment'], name='assets_raya_environ_b43ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='rayadatacentervm',
            index=models.Index(fields=['contract_end'], name='assets_raya_contrac_e6cca0_idx'),
        ),
        migrations.AddIndex(
            model_name='rayadatacentervm',
            index=models.Index(fields=['renewal_date'], name='assets_raya_renewal_539a74_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['branch', 'status'], name='assets_rout_branch__a2b608_idx'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['branch', 'status'], name='assets_scre_branch__6cd9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['branch', 'status'], name='assets_serv_branch__5ea76f_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['hostname'], name='assets_serv_hostnam_3dbec9_idx'),
        ),
        migrations.AddIndex(
            model_name='switch',
            index=models.Index(fields=['branch', 'status'], name='assets_swit_branch__206261_idx'),
        ),
        migrations.AddIndex(
            model_name='telephone',
            index=models.Index(fields=['branch', 'status'], name='assets_tele_branch__ad4520_idx'),
        ),
        migrations.AddIndex(
            model_name='ups',
            index=models.Index(fields=['branch', 'status'], name='assets_ups_branch__d36f93_idx'),
        ),
        migrations.AddIndex(
            model_name='ups',
            index=models.Index(fields=['next_maintenance_date'], name='assets_ups_next_ma_48fd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['server', 'status'], name='assets_virt_server__5f690c_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['environment'], name='assets_virt_environ_d53e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='zkdevice',
            index=models.Index(fields=['branch', 'status'], name='assets_zkde_branch__842155_idx'),
        ),
        migrations.AddIndex(
            model_name='zkdevice',
            index=models.Index(fields=['device_type'], name='assets_zkde_device__747ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='zkdevice',
            index=models.Index(fields=['ip_address'], name='assets_zkde_ip_addr_7c852b_idx'),
        ),
        migrations.AddField(
            model_name='laptopstorage',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_devices', to='assets.laptop'),
        ),
        migrations.AddField(
            model_name='laptoplog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.branch'),
        ),
        migrations.AddField(
            model_name='laptoplog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laptoplog',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.laptop'),
        ),
        migrations.AddField(
            model_name='laptoplog',
            name='new_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_new_employee_logs', to='assets.employee'),
        ),
        migrations.AddField(
            model_name='laptoplog',
            name='old_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_old_employee_logs', to='assets.employee'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='assets.branch'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_laptops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laptop',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='assets.employee'),
        ),
        migrations.AddField(
            model_name='desktopstorage',
            name='desktop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_devices', to='assets.desktop'),
        ),
        migrations.AddField(
            model_name='desktoplog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.branch'),
        ),
        migrations.AddField(
            model_name='desktoplog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desktoplog',
            name='desktop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.desktop'),
        ),
        migrations.AddField(
            model_name='desktoplog',
            name='new_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop_new_employee_logs', to='assets.employee'),
        ),
        migrations.AddField(
            model_name='desktoplog',
            name='old_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop_old_employee_logs', to='assets.employee'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktops', to='assets.branch'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_desktops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desktop',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktops', to='assets.employee'),
        ),
        migrations.AddIndex(
            model_name='laptop',
            index=models.Index(fields=['branch', 'status'], name='assets_lapt_branch__5e8594_idx'),
        ),
        migrations.AddIndex(
            model_name='laptop',
            index=models.Index(fields=['employee', 'status'], name='assets_lapt_employe_802dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='desktop',
            index=models.Index(fields=['branch', 'status'], name='assets_desk_branch__1e2657_idx'),
        ),
        migrations.AddIndex(
            model_name='desktop',
            index=models.Index(fields=['employee', 'status'], name='assets_desk_employe_2c65f7_idx'),
        ),
        migrations.RunPython(copy_assets, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AssetLog',
        ),
        migrations.DeleteModel(
            name='StorageDevice',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
